- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
    - name: Print some debug information
      debug: 
        msg: "Stub for provisioning new instance {{ EC2_NAME }} in Ansible"       
      tags: debug_info

