- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
    - name: Print some debug information 
      vars: 
        msg: |
          
          HOST Variables ("hostvars"):
          --------------------------------
          hostvars["ec2_name"] | to_nice_json }}
    
      debug: 
        msg: "{{ msg.split('\n') }}"       
      tags: debug_info

