- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
    - name: Print some debug information
      debug: 
        msg: "{{ EC2_NAME }}"       
      tags: debug_info

